image: node:11.15.0

stages:
  - format
  - build
  # - test
  - test-deploy
  - prod-deploy

# this gets run before anything else
before_script:
  - npm install

format:
  stage: format
  script:
    - npm run lintfix

build:
  stage: build
  script:
    - npm run build
  artifacts: #describes a path to the build result. The files in this path can be used in the next build steps
    expire_in: 1 week
    paths:
      - dist
      - .out
  dependencies:
    - format

# test:
#   stage: test
#   script:
#     - npm run test
#   artifacts:
#     when: always  # save test results even when the task fails
#     expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
#     paths:
#       - '.\TestResult.xml'  # saving NUnit results to copy to deploy folder
#   dependencies:
#     - format
#     - build

test-deploy:
  stage: test-deploy
  only:
    - testing
  script:
    - npm install -g firebase-tools
    - firebase use default --token $FIREBASE_DEPLOY_KEY
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY

  dependencies:
    - format
    - build
    - test

prod-deploy:
  stage: prod-deploy
  only:
    - master
  script:
    - npm install -g firebase-tools
    - firebase use production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY

  dependencies:
    - format
    - build
    - test